default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: mosque_development

test:
  <<: *default
  database: mosque_test

production:
  <<: *default
  database: mosque_production
  username: mosque
  password: <%= ENV['MOSQUE_DATABASE_PASSWORD'] %>
